language: node_js
node_js:
- '6'
- '8'
branches:
  except:
  - latest
  - production
  - /^v[0-9]\.[0-9]\.[0-9]$/
before_script:
- npm install -g grunt-cli
- ./create_config.sh
script:
- npm test
- node lib/run --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID} --clientSecret ${SPHERE_CLIENT_SECRET}
sudo: false
